### ISSUE TITLE
Require Java 8 for RPC client module?

### ISSUE THREAD

**Issue by msgilligan** [ConsensusJ/consensusj#15]
Is anyone using the RPC client in an environment that won't run code written with Lambdas and Default Interface Methods? I'm thinking the client can be somewhat simplified (with no loss of functionality) by using some Java 8 features.

**Comment by msgilligan** [comment]
@dexX7 Any thoughts on this?

@JeremyRand Would a change to Java 8 affect you?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 06/26/2016 10:44 PM, Sean Gilligan wrote:
> @JeremyRand <https://github.com/JeremyRand> Would a change to Java 
> 8 affect you?

At the moment I'm only using bitcoinj-daemon, which appears to already
require Java 8.  So I doubt this would affect me in any way.

That said, ideally I'd like to be able to support Debian Jessie
(without backports) and various versions of Android which don't
support Java 8.  So it'd actually be cool if it were feasible to run
bitcoinj-daemon with Java 7.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJXcKkQAAoJEAHN/EbZ1y06I9MQAK+TJwWmdUhyLlzELtL9hC0s
4vRUO6a1V7vFBksL31d+MsRSZF6tDw69GoWi42dg8oS35BLX5HgKcU+729avx335
Ky9GdWXpztToIbXQLTTNayuHuqOe+jC8wjQqMdZl3f16MLUZTOnu154opkuQCIRo
VfbJn4gk+ck4YHd5PNjzn8hY9W6Vtwcl1PK4DtzAgtCgxRdE0h7WN68fxybh9o4l
ncWCEkaHjaU35+aA/w+xwn+sYAsULv1K4f9tdP3lgD66q3UKC3fub/EQx3VxyaJ0
ZuTnKYw3sS0iUKYZEa7wb0ZhzS7ET2JpwDMVjWaKaAC7dDbgagHTKNrXjeUg/KNg
uHmjPpsfmuRcCCOHTwVHRZZmUSHqY54h15VAgl84oP8MB3Kw4lJOMjPV7J5Pw/bA
w+76YoyHH2TmjLERMDnhcEvHSiXtadKAT2HdMCtWf+qNp6zCJgmTmiiZuKyEcMj6
atpbtH3FqQW9k3oJRI1g2es3lLDLfOtYgrztew1aHjnI6I7Bkl0XKxqvobNFUrbC
9JLV5ktwfJmuKXkaL551uGellPFbeileZviTIK7L2OaQOgFjVtUPSWnuZzvIxdo9
5tdhTPxJwH4sB407J1fKjNiZF+5URFV+TkTA/aJ1lMtcBAFsonf2hiRDYcQVwCWv
hKqQct5wJ6TeKCAka61i
=a7jE
-----END PGP SIGNATURE-----

**Comment by msgilligan** [comment]
Interesting, @JeremyRand. My initial thoughts were that few people would want to run a server in an environment without Java 8 and that nobody would ever want to run a server on Android. The client however seemed like a candidate for Android. However I'm now thinking few Android apps would want to use a JSON-RPC client -- most are going to want REST or P2P.

Since you have the only known real-world application for the daemon -- and a quick test shows it compiles and runs with Java 7, I'm definitely open to the change.

Personally, I'm really loving Java 8 and the more readable code you can write with it. In the case of the RPC Client I see a potential for some cleanup with Java 8 which is why I opened this issue.

**Comment by dexX7** [comment]
I'd prefer Java 8, but if we can make things easier for certain applications, if we continue to use Java 7, then this should have priority.

**Comment by msgilligan** [comment]
According to Google as of January 8, 2018, 27% of Android users are on Android 7 Nougat or later and this is increasing at a few percentage points per month. Amongst cryptocurrency users/developers the percentage will is much higher. Given that the ConsensusJ-based apps I know about are months away from production release (and are in many cases going to require Android 7, themselves), I'd say the benefits of Java 8 greatly outweigh a mostly theoretical loss of market share.

@JeremyRand @dexX7 any update thoughts as of January 2018.

**Comment by JeremyRand** [comment]
@msgilligan A lot of security-focused or freedom-focused users (myself included) are on Replicant, which currently is based on Android 6.0.  Until Replicant releases a new version based on Android 7 or higher, I am likely to continue supporting Java 7 compatibility.

**Comment by msgilligan** [comment]
Implemented in PR #52

**Comment by msgilligan** [comment]
As of [v0.4.0](https://github.com/ConsensusJ/consensusj/blob/master/CHANGELOG.adoc#v040) all modules require JDK 8+
