### ISSUE TITLE
replace bitcoin-cli signtransaction with bitcoinj

### ISSUE THREAD

**Issue by Yucheng123** [ConsensusJ/consensusj#39]
we try to use bitcionj to sign the hex string from bitcoin-cli createrawtransaction and then broadcast transaction with bitcoin-cli. i wonder if there some ways?

**Comment by msgilligan** [comment]
If I understand your use case correctly, there is no need for you to use the `-cli` module. You can use BitcoinClient (now in `cjbtc-jsonrpc` module) directly to do what you want. But you could also do everything with bitcoinj itself and not using ConsensusJ at all.

bitcoinj can create transactions directly and send them via P2P. Use ConsensusJ if you want to use RPC to tell  Bitcoin Core node to broadcast them to the network or if you want Bitcoin Core to store the private keys in it's wallet file.

Reporting an issue is not the best way to ask for help though (though I haven't really offered an alternative, have I?) -- I'm going to close this issue, but feel free to ask a follow-up question on the closed issue.

**Comment by Yucheng123** [comment]
sorry , i ask the question on the group,thank you for your help
