### ISSUE TITLE
I want to use jsonrpc to connect bitcoind. What should I do?

### ISSUE THREAD

**Issue by vae520283995** [ConsensusJ/consensusj#53]
I want to use jsonrpc to connect bitcoind. What should I do?
Can you give me an example?

**Comment by msgilligan** [comment]
Create an instance of [BitcoinClient](https://consensusj.github.io/consensusj/apidoc/com/msgilligan/bitcoinj/rpc/BitcoinClient.html) and then start calling the methods you want to use. You'll need to provide URL, port, username, password to connect, of course.

Something like this:

```
    URI server = new URI("http://server.domain.tld:8332");  
    BitcoinClient client = new BitcoinClient(MainNetParams.get(), server, "username", "password");
    Integer count = client.getBlockCount();
```

**Comment by msgilligan** [comment]
Long term the answer to this question should be provided by #21 and #54 .
