### ISSUE TITLE
Rename this Project?

### ISSUE THREAD

**Issue by msgilligan** [ConsensusJ/consensusj#8]
I'm already having second thoughts about the project name. I'm not in a big hurry to rename it, but am opening an issue where suggestions can be made.

(In the short run I want to finish the Jackson work and then announce on but **bitcoinj** mailing list and see what kind of feedback and suggestions we get.)

**Comment by dexX7** [comment]
I always thought the name `bitcoinj-addons` is too close to `bitcoinj` (the project), and even though `bitcoinj` is used here, it's an open question, whether this project remains closely linked to `bitcoinj`, or whether it's scope goes beyond that at some point.

On the other hand, the gem of the project is probably the `bitcoinj-rpcclient`, which is indeed very related to `bitcoinj`.

**Comment by msgilligan** [comment]
Yeah, the current gem of the project is the rpcclient, but if we make progress on bidirectional JSON mapping and on the server that may become equally, or perhaps more significant.

Take a look at https://github.com/bitcoinj/bitcoinj/issues/895 -- you'll see what people are looking for in RPC client/server support for bitcoinj and also that @mikehearn was OK with the bitcoinj-addons name. It was always may intention to flush this stuff out and submit one or more modules to the bitcoinj project. Though @mikehearn is focusing on Bitcoin XT these days and @schildbach is now leading the project.

My plan is:

1. Finish improving the Jackson mapping in the client (and do a little bit more work on the server)
1. Send an email to the *bitcoinj* list announcing the project and asking for feedback and, more importantly, seeing whether and how it could be submitted/merged into *bitcoinj*.  (Given our multi project Gradle build maybe they'd just move the whole repo under the *bitcoinj* organization -- I really have no idea what feedback we'd get though.)
1. Choose a new name or names after receiving the feedback.

It will also be interesting to see if anyone volunteers to help -- or sponsor :) -- any of this work.

**Comment by stokito** [comment]
It's also confused that in `addons` contains a lot of child projects. I think it would be better to rename it to `incubator` or `shelter` or even split to several projects.

**Comment by msgilligan** [comment]
I like keeping it in a single Git repository with a single, Gradle, multi-project build. The README contains a [Modules section](https://github.com/msgilligan/bitcoinj-addons#modules) that explains the different modules. I need to approach bitcoinj and see if they want to take some or all of the modules and then make some decisions after that.

Another reason I created so many modules is so that individual jars can be used without pulling in unwanted transitive dependencies.

**Comment by msgilligan** [comment]
I'm leaning towards **ConsensusJ** and have reserved both the Github Organization name and the domain `ConsensusJ.org`.

**Comment by msgilligan** [comment]
Project moved to the [ConsensusJ](https://github.com/ConsensusJ) Github organization.
Repository renamed to https://github.com/ConsensusJ/consensusj
